main: me.zombie_striker.landclaiming.LandClaiming
version: 1.4.11-RF1
name: LandClaiming-RF
api-version: 1.14
commands:
   claim:
      description: Claims land
   unclaim:
      description: Unclaims land
   lock:
      description: Locks blocks
   unlock:
      description: Unlocks blocks
author:
   Zombie_Striker (with modifications by the Red Fusion Team)
permissions:
   landclaim.*:
     description: Gives access to all Inferno commands
     children:
       landclaim.default: true
       landclaim.admin: true
   landclaim.admin:
     description: Gives access to all Inferno commands
     children:
       landclaim.default: true